/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMA_H_RPCGEN
#define _SUMA_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct argumentos {
	int a;
	int b;
};
typedef struct argumentos argumentos;
#ifdef __cplusplus
extern "C" bool_t xdr_argumentos(XDR *, argumentos*);
#elif __STDC__
extern  bool_t xdr_argumentos(XDR *, argumentos*);
#else /* Old Style C */
bool_t xdr_argumentos();
#endif /* Old Style C */


#define SUMAR ((rpc_uint)99)
#define SUMAVER ((rpc_uint)1)

#ifdef __cplusplus
#define SUMA ((rpc_uint)1)
extern "C" int * suma_1(argumentos *, CLIENT *);
extern "C" int * suma_1_svc(argumentos *, struct svc_req *);
#define RESTA ((rpc_uint)2)
extern "C" int * resta_1(argumentos *, CLIENT *);
extern "C" int * resta_1_svc(argumentos *, struct svc_req *);

#elif __STDC__
#define SUMA ((rpc_uint)1)
extern  int * suma_1(argumentos *, CLIENT *);
extern  int * suma_1_svc(argumentos *, struct svc_req *);
#define RESTA ((rpc_uint)2)
extern  int * resta_1(argumentos *, CLIENT *);
extern  int * resta_1_svc(argumentos *, struct svc_req *);

#else /* Old Style C */
#define SUMA ((rpc_uint)1)
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA ((rpc_uint)2)
extern  int * resta_1();
extern  int * resta_1_svc();
#endif /* Old Style C */

#endif /* !_SUMA_H_RPCGEN */
