/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "suma.h"

bool_t
xdr_argumentos(XDR *xdrs, argumentos *objp)
{

	if (!xdr_int(xdrs, &objp->a))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->b))
		return (FALSE);
	return (TRUE);
}
