/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"

int *suma_1(argp, rqstp)
	argumentos *argp;
	struct svc_req *rqstp;
{

	static int  result;

	result = argp->a+argp->b;

	return(&result);
}

int *resta_1(argp, rqstp)
	argumentos *argp;
	struct svc_req *rqstp;
{

	static int  result;

	result = argp->a-argp->b;

	return(&result);
}
