/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"


void
sumar_1(host)
char *host;
{
	CLIENT *clnt;
	int  *result_1;
	argumentos  suma_1_arg;
	int  *result_2;
	argumentos  resta_1_arg;

	#ifndef DEBUG
	clnt = clnt_create(host, SUMAR, SUMAVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	#endif
	suma_1_arg.a=5;
	suma_1_arg.b=2;

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("La suma es: %d \n", *result_1);

	resta_1_arg.a=5;
	resta_1_arg.b=2;

	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("La resta es: %d \n", *result_2);
	
	#ifndef DEBUG	
	clnt_destroy( clnt );
	#endif
}


main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	sumar_1( host );
}
